name: test

on:
  pull_request:
    branches: [ "main", "develop" ]
    paths-ignore: [ "**.md" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        config: [
          { target: android, os: ubuntu-latest, tasks: testDebugUnitTest testReleaseUnitTest, continueOnError: false },
          { target: apple, os: macos-latest, tasks: iosX64Test iosSimulatorArm64Test macosX64Test macosArm64Test tvosX64Test tvosSimulatorArm64Test, continueOnError: false },
          { target: js, os: ubuntu-latest, tasks: jsTest wasmJsTest, continueOnError: false },
          { target: desktop, os: ubuntu-latest, tasks: jvmTest, continueOnError: false },
          { target: windows, os: windows-latest, tasks: mingwX64Test, continueOnError: false },
          { target: linux, os: ubuntu-latest, tasks: linuxX64Test, continueOnError: false },
        ]
    runs-on: ${{ matrix.config.os }}
    name: Test ${{ matrix.config.target }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Run tests for ${{ matrix.config.tasks }} on ${{ matrix.config.target }}
        continue-on-error: ${{ matrix.config.continueOnError }}
        run: |
          ./gradlew ${{ matrix.config.tasks }}
        shell: bash
        working-directory: ${{ github.workspace }}

      - name: Upload test results from ksoup-test module if failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.config.target }}
          path: charset-ext/build/reports/tests/**/*